#ifndef EVENTCONTROLMOCKTHREAD_EVENTCONTROLMOCK_EVENTCONTROLMOCKTHREAD_ADAPTER_H
#define EVENTCONTROLMOCKTHREAD_EVENTCONTROLMOCK_EVENTCONTROLMOCKTHREAD_ADAPTER_H

#include <all.h>

Unit rts_EventControl_EventControlMockThread_eventControlMock_eventControlMockThread_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit rts_EventControl_EventControlMockThread_eventControlMock_eventControlMockThread_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit rts_EventControl_EventControlMockThread_eventControlMock_eventControlMockThread_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints rts_EventControl_EventControlMockThread_eventControlMock_eventControlMockThread_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
