#include <EventControlMockThread_eventControlMock_eventControlMockThread_adapter.h>

Unit rts_EventControl_EventControlMockThread_eventControlMock_eventControlMockThread_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "EventControlMockThread_eventControlMock_eventControlMockThread_adapter.c", "", "rts_EventControl_EventControlMockThread_eventControlMock_eventControlMockThread_adapter_initialiseArchitecture", 0);

  rts_EventControlMockThread_eventControlMock_eventControlMockThread_eventControlMockThread_seL4App_initialiseArchitecture(SF_LAST);
}

Unit rts_EventControl_EventControlMockThread_eventControlMock_eventControlMockThread_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "EventControlMockThread_eventControlMock_eventControlMockThread_adapter.c", "", "rts_EventControl_EventControlMockThread_eventControlMock_eventControlMockThread_adapter_initialiseEntryPoint", 0);

  rts_EventControlMockThread_eventControlMock_eventControlMockThread_eventControlMockThread_seL4App_initialiseEntryPoint(SF_LAST);
}

Unit rts_EventControl_EventControlMockThread_eventControlMock_eventControlMockThread_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "EventControlMockThread_eventControlMock_eventControlMockThread_adapter.c", "", "rts_EventControl_EventControlMockThread_eventControlMock_eventControlMockThread_adapter_computeEntryPoint", 0);

  rts_EventControlMockThread_eventControlMock_eventControlMockThread_eventControlMockThread_seL4App_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints rts_EventControl_EventControlMockThread_eventControlMock_eventControlMockThread_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "EventControlMockThread_eventControlMock_eventControlMockThread_adapter.c", "", "rts_EventControl_EventControlMockThread_eventControlMock_eventControlMockThread_adapter_entryPoints", 0);

  return rts_EventControlMockThread_eventControlMock_eventControlMockThread_eventControlMockThread_seL4App_entryPoints(SF_LAST);
}
