#ifndef COINCIDENCELOGIC_ACTUATIONSUBSYSTEM_ACTUATIONUNIT1_TEMPERATURELOGIC_COINCIDENCELOGIC_ADAPTER_H
#define COINCIDENCELOGIC_ACTUATIONSUBSYSTEM_ACTUATIONUNIT1_TEMPERATURELOGIC_COINCIDENCELOGIC_ADAPTER_H

#include <all.h>

Unit rts_Actuation_CoincidenceLogic_actuationSubsystem_actuationUnit1_temperatureLogic_coincidenceLogic_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit rts_Actuation_CoincidenceLogic_actuationSubsystem_actuationUnit1_temperatureLogic_coincidenceLogic_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit rts_Actuation_CoincidenceLogic_actuationSubsystem_actuationUnit1_temperatureLogic_coincidenceLogic_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints rts_Actuation_CoincidenceLogic_actuationSubsystem_actuationUnit1_temperatureLogic_coincidenceLogic_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
