#include <CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter.h>

Unit rts_Actuation_CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter.c", "", "rts_Actuation_CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter_initialiseArchitecture", 0);

  rts_CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_coincidenceLogic_seL4App_initialiseArchitecture(SF_LAST);
}

Unit rts_Actuation_CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter.c", "", "rts_Actuation_CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter_initialiseEntryPoint", 0);

  rts_CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_coincidenceLogic_seL4App_initialiseEntryPoint(SF_LAST);
}

Unit rts_Actuation_CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter.c", "", "rts_Actuation_CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter_computeEntryPoint", 0);

  rts_CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_coincidenceLogic_seL4App_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints rts_Actuation_CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter.c", "", "rts_Actuation_CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_adapter_entryPoints", 0);

  return rts_CoincidenceLogic_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_coincidenceLogic_seL4App_entryPoints(SF_LAST);
}
