#ifndef ORLOGIC_ACTUATIONSUBSYSTEM_ACTUATIONUNIT1_TEMPPRESSURETRIPOUT_ORLOGIC_ADAPTER_H
#define ORLOGIC_ACTUATIONSUBSYSTEM_ACTUATIONUNIT1_TEMPPRESSURETRIPOUT_ORLOGIC_ADAPTER_H

#include <all.h>

Unit rts_Actuation_OrLogic_actuationSubsystem_actuationUnit1_tempPressureTripOut_orLogic_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit rts_Actuation_OrLogic_actuationSubsystem_actuationUnit1_tempPressureTripOut_orLogic_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit rts_Actuation_OrLogic_actuationSubsystem_actuationUnit1_tempPressureTripOut_orLogic_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints rts_Actuation_OrLogic_actuationSubsystem_actuationUnit1_tempPressureTripOut_orLogic_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
