#ifndef ACTUATORSMOCKTHREAD_ACTUATORSMOCK_ACTUATORSMOCKTHREAD_ADAPTER_H
#define ACTUATORSMOCKTHREAD_ACTUATORSMOCK_ACTUATORSMOCKTHREAD_ADAPTER_H

#include <all.h>

Unit rts_Actuators_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit rts_Actuators_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit rts_Actuators_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints rts_Actuators_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
