#include <ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter.h>

Unit rts_Actuators_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter.c", "", "rts_Actuators_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter_initialiseArchitecture", 0);

  rts_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_actuatorsMockThread_seL4App_initialiseArchitecture(SF_LAST);
}

Unit rts_Actuators_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter.c", "", "rts_Actuators_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter_initialiseEntryPoint", 0);

  rts_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_actuatorsMockThread_seL4App_initialiseEntryPoint(SF_LAST);
}

Unit rts_Actuators_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter.c", "", "rts_Actuators_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter_computeEntryPoint", 0);

  rts_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_actuatorsMockThread_seL4App_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints rts_Actuators_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter.c", "", "rts_Actuators_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_adapter_entryPoints", 0);

  return rts_ActuatorsMockThread_actuatorsMock_actuatorsMockThread_actuatorsMockThread_seL4App_entryPoints(SF_LAST);
}
